### ISSUE TITLE
bug: stopped reading from source

### ISSUE THREAD

**Issue by DemianD** [DemianD/ugent-master-thesis-matrix-profile#7]
The SourceReader stopped fetching new observations, due to an rmlmapper-error or connection-error. 

```
(node:25890) UnhandledPromiseRejectionWarning: Error: Error while executing the rules.
    at /home/demian-web/masterproef/ssn-server/packages/ssn-core/node_modules/@rmlio/rmlmapper-java-wrapper/lib/wrapper.js:95:35
    at ChildProcess.exithandler (child_process.js:310:5)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1026:16)
    at Socket.<anonymous> (internal/child_process.js:441:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:674:12)
(node:25890) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:25890) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:25890) UnhandledPromiseRejectionWarning: Error: Error while executing the rules.
    at /home/demian-web/masterproef/ssn-server/packages/ssn-core/node_modules/@rmlio/rmlmapper-java-wrapper/lib/wrapper.js:95:35
    at ChildProcess.exithandler (child_process.js:310:5)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1026:16)
    at Socket.<anonymous> (internal/child_process.js:441:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:674:12)
(node:25890) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:25890) UnhandledPromiseRejectionWarning: Error: write ECONNRESET
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:92:16)
(node:25890) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:25890) UnhandledPromiseRejectionWarning: Error: write ECONNRESET
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:92:16)
(node:25890) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:25890) UnhandledPromiseRejectionWarning: Error: write ECONNRESET
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:92:16)
(node:25890) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
(node:25890) UnhandledPromiseRejectionWarning: Error: write ECONNRESET
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:92:16)
(node:25890) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
(node:25890) UnhandledPromiseRejectionWarning: Error: write ECONNRESET
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:92:16)
(node:25890) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)
(node:25890) UnhandledPromiseRejectionWarning: Error: write ECONNRESET
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:92:16)
(node:25890) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)
```

**Comment by DemianD** [comment]
```
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 65536 bytes for committing reserved memory.
# Possible reasons:
#   The system is out of physical RAM or swap space
#   The process is running with CompressedOops enabled, and the Java Heap may be blocking the growth of the native heap
# Possible solutions:
#   Reduce memory load on the system
#   Increase physical memory or swap space
#   Check if swap backing store is full
#   Decrease Java heap size (-Xmx/-Xms)
#   Decrease number of Java threads
#   Decrease Java thread stack sizes (-Xss)
#   Set larger code cache with -XX:ReservedCodeCacheSize=
#   JVM is running with Unscaled Compressed Oops mode in which the Java heap is
#     placed in the first 4GB address space. The Java Heap base address is the
#     maximum limit for the native heap growth. Please use -XX:HeapBaseMinAddress
#     to set the Java Heap base and to place the Java Heap above 4GB virtual address.
# This output file may be truncated or incomplete.
#
#  Out of Memory Error (os_linux.cpp:2757), pid=23841, tid=0x00007ff987efe700
#
# JRE version: OpenJDK Runtime Environment (8.0_242-b08) (build 1.8.0_242-8u242-b08-0ubuntu3~18.04-b08)
# Java VM: OpenJDK 64-Bit Server VM (25.242-b08 mixed mode linux-amd64 compressed oops)
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
```

```
Memory: 4k page, physical 1009176k(304352k free), swap 0k(0k free)

vm_info: OpenJDK 64-Bit Server VM (25.242-b08) for linux-amd64 JRE (1.8.0_242-8u242-b08-0ubuntu3~18.04-b08), built on Jan 17 2020 23:41:21 by "buildd" with gcc 7.4.0

time: Sat Apr 18 03:55:13 2020
timezone: UTC
elapsed time: 54 seconds (0d 0h 0m 54s)
```

**Comment by DemianD** [comment]
Latest observations before crash (last observation is after the restart of the server)

```turtle
<https://mp-server.dem.be/P01/numberOfVacantParkingSpaces/member/2020-04-18T03:54:34.081Z> a <http://www.w3.org/ns/sosa/Observation>;
    <http://www.w3.org/ns/sosa/observedProperty> <http://vocab.datex.org/terms#numberOfVacantParkingSpaces>;
    <http://www.w3.org/ns/sosa/hasSimpleResult> "67"^^<http://www.w3.org/2001/XMLSchema#integer>;
    <http://www.w3.org/ns/sosa/hasFeatureOfInterest> <https://mp-server.dem.be/P01>;
    <http://www.w3.org/ns/sosa/resultTime> "2020-04-18T03:54:34.081Z"^^<http://www.w3.org/2001/XMLSchema#dateTime>.
<https://mp-server.dem.be/P01/numberOfVacantParkingSpacesSeries> <https://w3id.org/tree#member> <https://mp-server.dem.be/P01/numberOfVacantParkingSpaces/member/2020-04-18T03:54:34.081Z>.
<https://mp-server.dem.be/P01/numberOfVacantParkingSpaces/member/2020-04-18T03:57:20.054Z> a <http://www.w3.org/ns/sosa/Observation>;
    <http://www.w3.org/ns/sosa/observedProperty> <http://vocab.datex.org/terms#numberOfVacantParkingSpaces>;
    <http://www.w3.org/ns/sosa/hasSimpleResult> "67"^^<http://www.w3.org/2001/XMLSchema#integer>;
    <http://www.w3.org/ns/sosa/hasFeatureOfInterest> <https://mp-server.dem.be/P01>;
    <http://www.w3.org/ns/sosa/resultTime> "2020-04-18T03:57:20.054Z"^^<http://www.w3.org/2001/XMLSchema#dateTime>.
<https://mp-server.dem.be/P01/numberOfVacantParkingSpacesSeries> <https://w3id.org/tree#member> <https://mp-server.dem.be/P01/numberOfVacantParkingSpaces/member/2020-04-18T03:57:20.054Z>.
<https://mp-server.dem.be/P01/numberOfVacantParkingSpaces/member/2020-04-18T03:57:20.116Z> a <http://www.w3.org/ns/sosa/Observation>;
    <http://www.w3.org/ns/sosa/observedProperty> <http://vocab.datex.org/terms#numberOfVacantParkingSpaces>;
    <http://www.w3.org/ns/sosa/hasSimpleResult> "67"^^<http://www.w3.org/2001/XMLSchema#integer>;
    <http://www.w3.org/ns/sosa/hasFeatureOfInterest> <https://mp-server.dem.be/P01>;
    <http://www.w3.org/ns/sosa/resultTime> "2020-04-18T03:57:20.116Z"^^<http://www.w3.org/2001/XMLSchema#dateTime>.
<https://mp-server.dem.be/P01/numberOfVacantParkingSpacesSeries> <https://w3id.org/tree#member> <https://mp-server.dem.be/P01/numberOfVacantParkingSpaces/member/2020-04-18T03:57:20.116Z>.
<https://mp-server.dem.be/P01/numberOfVacantParkingSpaces/member/2020-04-18T03:57:20.156Z> a <http://www.w3.org/ns/sosa/Observation>;
    <http://www.w3.org/ns/sosa/observedProperty> <http://vocab.datex.org/terms#numberOfVacantParkingSpaces>;
    <http://www.w3.org/ns/sosa/hasSimpleResult> "67"^^<http://www.w3.org/2001/XMLSchema#integer>;
    <http://www.w3.org/ns/sosa/hasFeatureOfInterest> <https://mp-server.dem.be/P01>;
    <http://www.w3.org/ns/sosa/resultTime> "2020-04-18T03:57:20.156Z"^^<http://www.w3.org/2001/XMLSchema#dateTime>.
<https://mp-server.dem.be/P01/numberOfVacantParkingSpacesSeries> <https://w3id.org/tree#member> <https://mp-server.dem.be/P01/numberOfVacantParkingSpaces/member/2020-04-18T03:57:20.156Z>.
<https://mp-server.dem.be/P01/numberOfVacantParkingSpaces/member/2020-04-18T03:57:20.172Z> a <http://www.w3.org/ns/sosa/Observation>;
    <http://www.w3.org/ns/sosa/observedProperty> <http://vocab.datex.org/terms#numberOfVacantParkingSpaces>;
    <http://www.w3.org/ns/sosa/hasSimpleResult> "67"^^<http://www.w3.org/2001/XMLSchema#integer>;
    <http://www.w3.org/ns/sosa/hasFeatureOfInterest> <https://mp-server.dem.be/P01>;
    <http://www.w3.org/ns/sosa/resultTime> "2020-04-18T03:57:20.172Z"^^<http://www.w3.org/2001/XMLSchema#dateTime>.
<https://mp-server.dem.be/P01/numberOfVacantParkingSpacesSeries> <https://w3id.org/tree#member> <https://mp-server.dem.be/P01/numberOfVacantParkingSpaces/member/2020-04-18T03:57:20.172Z>.
<https://mp-server.dem.be/P01/numberOfVacantParkingSpaces/member/2020-04-18T03:57:20.225Z> a <http://www.w3.org/ns/sosa/Observation>;
    <http://www.w3.org/ns/sosa/observedProperty> <http://vocab.datex.org/terms#numberOfVacantParkingSpaces>;
    <http://www.w3.org/ns/sosa/hasSimpleResult> "67"^^<http://www.w3.org/2001/XMLSchema#integer>;
    <http://www.w3.org/ns/sosa/hasFeatureOfInterest> <https://mp-server.dem.be/P01>;
    <http://www.w3.org/ns/sosa/resultTime> "2020-04-18T03:57:20.225Z"^^<http://www.w3.org/2001/XMLSchema#dateTime>.
<https://mp-server.dem.be/P01/numberOfVacantParkingSpacesSeries> <https://w3id.org/tree#member> <https://mp-server.dem.be/P01/numberOfVacantParkingSpaces/member/2020-04-18T03:57:20.225Z>.
<https://mp-server.dem.be/P01/numberOfVacantParkingSpaces/member/2020-04-18T03:57:20.318Z> a <http://www.w3.org/ns/sosa/Observation>;
    <http://www.w3.org/ns/sosa/observedProperty> <http://vocab.datex.org/terms#numberOfVacantParkingSpaces>;
    <http://www.w3.org/ns/sosa/hasSimpleResult> "67"^^<http://www.w3.org/2001/XMLSchema#integer>;
    <http://www.w3.org/ns/sosa/hasFeatureOfInterest> <https://mp-server.dem.be/P01>;
    <http://www.w3.org/ns/sosa/resultTime> "2020-04-18T03:57:20.318Z"^^<http://www.w3.org/2001/XMLSchema#dateTime>.
<https://mp-server.dem.be/P01/numberOfVacantParkingSpacesSeries> <https://w3id.org/tree#member> <https://mp-server.dem.be/P01/numberOfVacantParkingSpaces/member/2020-04-18T03:57:20.318Z>.
<https://mp-server.dem.be/P01/numberOfVacantParkingSpaces/member/2020-04-18T03:57:25.691Z> a <http://www.w3.org/ns/sosa/Observation>;
    <http://www.w3.org/ns/sosa/observedProperty> <http://vocab.datex.org/terms#numberOfVacantParkingSpaces>;
    <http://www.w3.org/ns/sosa/hasSimpleResult> "67"^^<http://www.w3.org/2001/XMLSchema#integer>;
    <http://www.w3.org/ns/sosa/hasFeatureOfInterest> <https://mp-server.dem.be/P01>;
    <http://www.w3.org/ns/sosa/resultTime> "2020-04-18T03:57:25.691Z"^^<http://www.w3.org/2001/XMLSchema#dateTime>.
<https://mp-server.dem.be/P01/numberOfVacantParkingSpacesSeries> <https://w3id.org/tree#member> <https://mp-server.dem.be/P01/numberOfVacantParkingSpaces/member/2020-04-18T03:57:25.691Z>.
<https://mp-server.dem.be/P01/numberOfVacantParkingSpaces/member/2020-04-18T03:57:25.729Z> a <http://www.w3.org/ns/sosa/Observation>;
    <http://www.w3.org/ns/sosa/observedProperty> <http://vocab.datex.org/terms#numberOfVacantParkingSpaces>;
    <http://www.w3.org/ns/sosa/hasSimpleResult> "67"^^<http://www.w3.org/2001/XMLSchema#integer>;
    <http://www.w3.org/ns/sosa/hasFeatureOfInterest> <https://mp-server.dem.be/P01>;
    <http://www.w3.org/ns/sosa/resultTime> "2020-04-18T03:57:25.729Z"^^<http://www.w3.org/2001/XMLSchema#dateTime>.
<https://mp-server.dem.be/P01/numberOfVacantParkingSpacesSeries> <https://w3id.org/tree#member> <https://mp-server.dem.be/P01/numberOfVacantParkingSpaces/member/2020-04-18T03:57:25.729Z>.
<https://mp-server.dem.be/P01/numberOfVacantParkingSpaces/member/2020-04-18T03:57:25.748Z> a <http://www.w3.org/ns/sosa/Observation>;
    <http://www.w3.org/ns/sosa/observedProperty> <http://vocab.datex.org/terms#numberOfVacantParkingSpaces>;
    <http://www.w3.org/ns/sosa/hasSimpleResult> "67"^^<http://www.w3.org/2001/XMLSchema#integer>;
    <http://www.w3.org/ns/sosa/hasFeatureOfInterest> <https://mp-server.dem.be/P01>;
    <http://www.w3.org/ns/sosa/resultTime> "2020-04-18T03:57:25.748Z"^^<http://www.w3.org/2001/XMLSchema#dateTime>.
<https://mp-server.dem.be/P01/numberOfVacantParkingSpacesSeries> <https://w3id.org/tree#member> <https://mp-server.dem.be/P01/numberOfVacantParkingSpaces/member/2020-04-18T03:57:25.748Z>.
<https://mp-server.dem.be/P01/numberOfVacantParkingSpaces/member/2020-04-18T03:57:25.822Z> a <http://www.w3.org/ns/sosa/Observation>;
    <http://www.w3.org/ns/sosa/observedProperty> <http://vocab.datex.org/terms#numberOfVacantParkingSpaces>;
    <http://www.w3.org/ns/sosa/hasSimpleResult> "67"^^<http://www.w3.org/2001/XMLSchema#integer>;
    <http://www.w3.org/ns/sosa/hasFeatureOfInterest> <https://mp-server.dem.be/P01>;
    <http://www.w3.org/ns/sosa/resultTime> "2020-04-18T03:57:25.822Z"^^<http://www.w3.org/2001/XMLSchema#dateTime>.
<https://mp-server.dem.be/P01/numberOfVacantParkingSpacesSeries> <https://w3id.org/tree#member> <https://mp-server.dem.be/P01/numberOfVacantParkingSpaces/member/2020-04-18T03:57:25.822Z>.
<https://mp-server.dem.be/P01/numberOfVacantParkingSpaces/member/2020-04-18T03:57:25.823Z> a <http://www.w3.org/ns/sosa/Observation>;
    <http://www.w3.org/ns/sosa/observedProperty> <http://vocab.datex.org/terms#numberOfVacantParkingSpaces>;
    <http://www.w3.org/ns/sosa/hasSimpleResult> "67"^^<http://www.w3.org/2001/XMLSchema#integer>;
    <http://www.w3.org/ns/sosa/hasFeatureOfInterest> <https://mp-server.dem.be/P01>;
    <http://www.w3.org/ns/sosa/resultTime> "2020-04-18T03:57:25.823Z"^^<http://www.w3.org/2001/XMLSchema#dateTime>.
<https://mp-server.dem.be/P01/numberOfVacantParkingSpacesSeries> <https://w3id.org/tree#member> <https://mp-server.dem.be/P01/numberOfVacantParkingSpaces/member/2020-04-18T03:57:25.823Z>.
<https://mp-server.dem.be/P01/numberOfVacantParkingSpaces/member/2020-04-18T03:57:25.843Z> a <http://www.w3.org/ns/sosa/Observation>;
    <http://www.w3.org/ns/sosa/observedProperty> <http://vocab.datex.org/terms#numberOfVacantParkingSpaces>;
    <http://www.w3.org/ns/sosa/hasSimpleResult> "67"^^<http://www.w3.org/2001/XMLSchema#integer>;
    <http://www.w3.org/ns/sosa/hasFeatureOfInterest> <https://mp-server.dem.be/P01>;
    <http://www.w3.org/ns/sosa/resultTime> "2020-04-18T03:57:25.843Z"^^<http://www.w3.org/2001/XMLSchema#dateTime>.
<https://mp-server.dem.be/P01/numberOfVacantParkingSpacesSeries> <https://w3id.org/tree#member> <https://mp-server.dem.be/P01/numberOfVacantParkingSpaces/member/2020-04-18T03:57:25.843Z>.
<https://mp-server.dem.be/P01/numberOfVacantParkingSpaces/member/2020-04-18T03:57:25.882Z> a <http://www.w3.org/ns/sosa/Observation>;
    <http://www.w3.org/ns/sosa/observedProperty> <http://vocab.datex.org/terms#numberOfVacantParkingSpaces>;
    <http://www.w3.org/ns/sosa/hasSimpleResult> "67"^^<http://www.w3.org/2001/XMLSchema#integer>;
    <http://www.w3.org/ns/sosa/hasFeatureOfInterest> <https://mp-server.dem.be/P01>;
    <http://www.w3.org/ns/sosa/resultTime> "2020-04-18T03:57:25.882Z"^^<http://www.w3.org/2001/XMLSchema#dateTime>.
<https://mp-server.dem.be/P01/numberOfVacantParkingSpacesSeries> <https://w3id.org/tree#member> <https://mp-server.dem.be/P01/numberOfVacantParkingSpaces/member/2020-04-18T03:57:25.882Z>.
<https://mp-server.dem.be/P01/numberOfVacantParkingSpaces/member/2020-04-18T03:57:25.899Z> a <http://www.w3.org/ns/sosa/Observation>;
    <http://www.w3.org/ns/sosa/observedProperty> <http://vocab.datex.org/terms#numberOfVacantParkingSpaces>;
    <http://www.w3.org/ns/sosa/hasSimpleResult> "67"^^<http://www.w3.org/2001/XMLSchema#integer>;
    <http://www.w3.org/ns/sosa/hasFeatureOfInterest> <https://mp-server.dem.be/P01>;
    <http://www.w3.org/ns/sosa/resultTime> "2020-04-18T03:57:25.899Z"^^<http://www.w3.org/2001/XMLSchema#dateTime>.
<https://mp-server.dem.be/P01/numberOfVacantParkingSpacesSeries> <https://w3id.org/tree#member> <https://mp-server.dem.be/P01/numberOfVacantParkingSpaces/member/2020-04-18T03:57:25.899Z>.
<https://mp-server.dem.be/P01/numberOfVacantParkingSpaces/member/2020-04-18T03:57:25.902Z> a <http://www.w3.org/ns/sosa/Observation>;
    <http://www.w3.org/ns/sosa/observedProperty> <http://vocab.datex.org/terms#numberOfVacantParkingSpaces>;
    <http://www.w3.org/ns/sosa/hasSimpleResult> "67"^^<http://www.w3.org/2001/XMLSchema#integer>;
    <http://www.w3.org/ns/sosa/hasFeatureOfInterest> <https://mp-server.dem.be/P01>;
    <http://www.w3.org/ns/sosa/resultTime> "2020-04-18T03:57:25.902Z"^^<http://www.w3.org/2001/XMLSchema#dateTime>.
<https://mp-server.dem.be/P01/numberOfVacantParkingSpacesSeries> <https://w3id.org/tree#member> <https://mp-server.dem.be/P01/numberOfVacantParkingSpaces/member/2020-04-18T03:57:25.902Z>.
<https://mp-server.dem.be/P01/numberOfVacantParkingSpaces/member/2020-04-18T03:57:25.903Z> a <http://www.w3.org/ns/sosa/Observation>;
    <http://www.w3.org/ns/sosa/observedProperty> <http://vocab.datex.org/terms#numberOfVacantParkingSpaces>;
    <http://www.w3.org/ns/sosa/hasSimpleResult> "67"^^<http://www.w3.org/2001/XMLSchema#integer>;
    <http://www.w3.org/ns/sosa/hasFeatureOfInterest> <https://mp-server.dem.be/P01>;
    <http://www.w3.org/ns/sosa/resultTime> "2020-04-18T03:57:25.903Z"^^<http://www.w3.org/2001/XMLSchema#dateTime>.
<https://mp-server.dem.be/P01/numberOfVacantParkingSpacesSeries> <https://w3id.org/tree#member> <https://mp-server.dem.be/P01/numberOfVacantParkingSpaces/member/2020-04-18T03:57:25.903Z>.
<https://mp-server.dem.be/P01/numberOfVacantParkingSpaces/member/2020-04-18T03:57:25.907Z> a <http://www.w3.org/ns/sosa/Observation>;
    <http://www.w3.org/ns/sosa/observedProperty> <http://vocab.datex.org/terms#numberOfVacantParkingSpaces>;
    <http://www.w3.org/ns/sosa/hasSimpleResult> "67"^^<http://www.w3.org/2001/XMLSchema#integer>;
    <http://www.w3.org/ns/sosa/hasFeatureOfInterest> <https://mp-server.dem.be/P01>;
    <http://www.w3.org/ns/sosa/resultTime> "2020-04-18T03:57:25.907Z"^^<http://www.w3.org/2001/XMLSchema#dateTime>.
<https://mp-server.dem.be/P01/numberOfVacantParkingSpacesSeries> <https://w3id.org/tree#member> <https://mp-server.dem.be/P01/numberOfVacantParkingSpaces/member/2020-04-18T03:57:25.907Z>.
<https://mp-server.dem.be/P01/numberOfVacantParkingSpaces/member/2020-04-18T03:57:25.909Z> a <http://www.w3.org/ns/sosa/Observation>;
    <http://www.w3.org/ns/sosa/observedProperty> <http://vocab.datex.org/terms#numberOfVacantParkingSpaces>;
    <http://www.w3.org/ns/sosa/hasSimpleResult> "67"^^<http://www.w3.org/2001/XMLSchema#integer>;
    <http://www.w3.org/ns/sosa/hasFeatureOfInterest> <https://mp-server.dem.be/P01>;
    <http://www.w3.org/ns/sosa/resultTime> "2020-04-18T03:57:25.909Z"^^<http://www.w3.org/2001/XMLSchema#dateTime>.
<https://mp-server.dem.be/P01/numberOfVacantParkingSpacesSeries> <https://w3id.org/tree#member> <https://mp-server.dem.be/P01/numberOfVacantParkingSpaces/member/2020-04-18T03:57:25.909Z>.
<https://mp-server.dem.be/P01/numberOfVacantParkingSpaces/member/2020-04-18T03:57:25.915Z> a <http://www.w3.org/ns/sosa/Observation>;
    <http://www.w3.org/ns/sosa/observedProperty> <http://vocab.datex.org/terms#numberOfVacantParkingSpaces>;
    <http://www.w3.org/ns/sosa/hasSimpleResult> "67"^^<http://www.w3.org/2001/XMLSchema#integer>;
    <http://www.w3.org/ns/sosa/hasFeatureOfInterest> <https://mp-server.dem.be/P01>;
    <http://www.w3.org/ns/sosa/resultTime> "2020-04-18T03:57:25.915Z"^^<http://www.w3.org/2001/XMLSchema#dateTime>.
<https://mp-server.dem.be/P01/numberOfVacantParkingSpacesSeries> <https://w3id.org/tree#member> <https://mp-server.dem.be/P01/numberOfVacantParkingSpaces/member/2020-04-18T03:57:25.915Z>.
<https://mp-server.dem.be/P01/numberOfVacantParkingSpaces/member/2020-04-18T03:57:25.916Z> a <http://www.w3.org/ns/sosa/Observation>;
    <http://www.w3.org/ns/sosa/observedProperty> <http://vocab.datex.org/terms#numberOfVacantParkingSpaces>;
    <http://www.w3.org/ns/sosa/hasSimpleResult> "67"^^<http://www.w3.org/2001/XMLSchema#integer>;
    <http://www.w3.org/ns/sosa/hasFeatureOfInterest> <https://mp-server.dem.be/P01>;
    <http://www.w3.org/ns/sosa/resultTime> "2020-04-18T03:57:25.916Z"^^<http://www.w3.org/2001/XMLSchema#dateTime>.
<https://mp-server.dem.be/P01/numberOfVacantParkingSpacesSeries> <https://w3id.org/tree#member> <https://mp-server.dem.be/P01/numberOfVacantParkingSpaces/member/2020-04-18T03:57:25.916Z>.
<https://mp-server.dem.be/P01/numberOfVacantParkingSpaces/member/2020-04-18T03:57:25.919Z> a <http://www.w3.org/ns/sosa/Observation>;
    <http://www.w3.org/ns/sosa/observedProperty> <http://vocab.datex.org/terms#numberOfVacantParkingSpaces>;
    <http://www.w3.org/ns/sosa/hasSimpleResult> "67"^^<http://www.w3.org/2001/XMLSchema#integer>;
    <http://www.w3.org/ns/sosa/hasFeatureOfInterest> <https://mp-server.dem.be/P01>;
    <http://www.w3.org/ns/sosa/resultTime> "2020-04-18T03:57:25.919Z"^^<http://www.w3.org/2001/XMLSchema#dateTime>.
<https://mp-server.dem.be/P01/numberOfVacantParkingSpacesSeries> <https://w3id.org/tree#member> <https://mp-server.dem.be/P01/numberOfVacantParkingSpaces/member/2020-04-18T03:57:25.919Z>.
<https://mp-server.dem.be/P01/numberOfVacantParkingSpaces/member/2020-04-18T03:57:25.922Z> a <http://www.w3.org/ns/sosa/Observation>;
    <http://www.w3.org/ns/sosa/observedProperty> <http://vocab.datex.org/terms#numberOfVacantParkingSpaces>;
    <http://www.w3.org/ns/sosa/hasSimpleResult> "67"^^<http://www.w3.org/2001/XMLSchema#integer>;
    <http://www.w3.org/ns/sosa/hasFeatureOfInterest> <https://mp-server.dem.be/P01>;
    <http://www.w3.org/ns/sosa/resultTime> "2020-04-18T03:57:25.922Z"^^<http://www.w3.org/2001/XMLSchema#dateTime>.
<https://mp-server.dem.be/P01/numberOfVacantParkingSpacesSeries> <https://w3id.org/tree#member> <https://mp-server.dem.be/P01/numberOfVacantParkingSpaces/member/2020-04-18T03:57:25.922Z>.
<https://mp-server.dem.be/P01/numberOfVacantParkingSpaces/member/2020-04-18T07:00:49.644Z> a <http://www.w3.org/ns/sosa/Observation>;
    <http://www.w3.org/ns/sosa/observedProperty> <http://vocab.datex.org/terms#numberOfVacantParkingSpaces>;
    <http://www.w3.org/ns/sosa/hasSimpleResult> "66"^^<http://www.w3.org/2001/XMLSchema#integer>;
    <http://www.w3.org/ns/sosa/hasFeatureOfInterest> <https://mp-server.dem.be/P01>;
    <http://www.w3.org/ns/sosa/resultTime> "2020-04-18T07:00:49.644Z"^^<http://www.w3.org/2001/XMLSchema#dateTime>.
<https://mp-server.dem.be/P01/numberOfVacantParkingSpacesSeries> <https://w3id.org/tree#member> <https://mp-server.dem.be/P01/numberOfVacantParkingSpaces/member/2020-04-18T07:00:49.644Z>.
```

**Comment by DemianD** [comment]
Observations were made every few milliseconds: 

```
2020-04-18T03:57:20.054Z
2020-04-18T03:57:20.116Z
2020-04-18T03:57:20.156Z
2020-04-18T03:57:20.172Z
2020-04-18T03:57:20.225Z
2020-04-18T03:57:20.318Z
2020-04-18T03:57:25.691Z
2020-04-18T03:57:25.729Z
2020-04-18T03:57:25.748Z
2020-04-18T03:57:25.822Z
2020-04-18T03:57:25.823Z
2020-04-18T03:57:25.843Z
2020-04-18T03:57:25.882Z
2020-04-18T03:57:25.899Z
2020-04-18T03:57:25.902Z
2020-04-18T03:57:25.903Z
2020-04-18T03:57:25.907Z
2020-04-18T03:57:25.909Z
2020-04-18T03:57:25.915Z
2020-04-18T03:57:25.916Z
2020-04-18T03:57:25.919Z
2020-04-18T03:57:25.922Z
```

**Comment by DemianD** [comment]
These dates are made here: https://github.com/DemianD/masterproef/blob/master/ssn-server/packages/ssn-example-parkings-gent/src/ParkingGentSourceReader.js#L20

So the `async run()` function is called a lot faster than what is specified with the interval
